name: 自动打包部署

on:
  push:
    branches:
      - master

jobs:
  build:
    # runs-on 指定job任何运行所需要的虚拟机环境(必填字段)
    runs-on: ubuntu-latest
    steps:
      # 获取源码
      - name: 迁出代码
        # 使用action库 actions/checkout获取源码
        uses: actions/checkout@master

      # 安装Node
      - name: 安装node.js
        # 使用action库 actions/setup-node安装node
        uses: actions/setup-node@v1
        with:
          node-version: 14.0.0

      #安装依赖
      - name: 安装依赖
        run: npm install

      - name: 打包
        run: npm run build

      # 上传到服务器
      - name: 发布到腾讯云
        uses: easingthemes/ssh-deploy@2.1.1
        env:
          # 私钥
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          # scp参数
          ARGS: '-avzr --delete'
          # 源目录
          SOURCE: 'dist'
          # 服务器ip
          REMOTE_HOST: '124.222.69.209'
          # 用户
          REMOTE_USER: 'root'
          # 目标地址
          TARGET: '/root/vue-in-action'
